urls:
	www.youtu.be:
		service: youtube
		request: "{id}"
	youtu.be:
		service: youtube
		request: "{id}"
	www.youtube.com:
		service: youtube
		request: "watch?v={id}"
	youtube.com:
		service: youtube
		request: "watch?v={id}"
	www.vimeo.com:
		service: vimeo
		request: "{id}"
	vimeo.com:
		service: vimeo
		request: "{id}"
services:
	youtube:
		embed: "<iframe width="{width}" height="{height}" src="http://www.youtube.com/embed/{id}?wmode=transparent" frameborder="0" allowfullscreen></iframe>"
	vimeo:
		embed: "<iframe src="http://player.vimeo.com/video/{id}?title=0&amp;byline=0&amp;portrait=0" width="{width}" height="{height}" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>"